#!/usr/bin/env bash
# Transpiles Claude Code agent definitions (*.md) into Codex agent definitions (*.toml).
# Source of truth stays in core/agents/ and web/agents/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-$REPO_ROOT/codex/agents}"

frontmatter() { awk 'NR==1 && $0=="---"{f=1; next} f && $0=="---"{exit} f' "$1"; }
body() { awk 'NR==1 && $0=="---"{f=1; next} f && $0=="---"{f=0; b=1; next} b' "$1"; }

field() { printf '%s\n' "$1" | sed -n "s/^$2: *//p" | head -n1; }

# Handles both `tools: A, B` and a YAML block sequence of `  - A` items.
tools_of() {
  printf '%s\n' "$1" | awk '
    /^tools:/ { sub(/^tools:[[:space:]]*/, ""); if (length($0)) print $0; intools=1; next }
    intools && /^[[:space:]]+-[[:space:]]*/ { sub(/^[[:space:]]+-[[:space:]]*/, ""); print $0; next }
    intools && /^[^[:space:]]/ { intools=0 }
  ' | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' || true
}

escape_basic() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

mkdir -p "$OUT_DIR"

# Clear stale output so a renamed or deleted agent does not linger as a committed
# .toml that install.sh would keep copying into ~/.codex/agents.
rm -f "$OUT_DIR"/*.toml

count=0
for src in "$REPO_ROOT"/core/agents/*.md "$REPO_ROOT"/web/agents/*.md; do
  fm="$(frontmatter "$src")"
  bd="$(body "$src")"

  name="$(field "$fm" name)"
  description="$(field "$fm" description)"
  model="$(field "$fm" model)"

  if [ -z "$name" ] || [ -z "$description" ]; then
    echo "error: $src is missing name or description" >&2
    exit 1
  fi

  if printf '%s' "$bd" | grep -q "'''"; then
    echo "error: $src body contains ''' and cannot be emitted as a TOML literal string" >&2
    exit 1
  fi

  if tools_of "$fm" | grep -qxE 'Write|Edit'; then
    sandbox="workspace-write"
  else
    sandbox="read-only"
  fi

  # `inherit` is a model name like any other; it just maps to "pin nothing", which
  # is how Codex spells "take the model from the session config".
  case "$model" in
    haiku)   codex_model="gpt-5.6-luna";  effort="low" ;;
    sonnet)  codex_model="gpt-5.6-terra"; effort="medium" ;;
    opus)    codex_model="gpt-5.6";       effort="high" ;;
    inherit) codex_model="";              effort="" ;;
    *) echo "error: $src has unknown model '$model'" >&2; exit 1 ;;
  esac

  {
    echo "# GENERATED by codex/transpile-agents.sh from $(basename "$(dirname "$(dirname "$src")")")/agents/$(basename "$src") — do not edit by hand."
    echo "name = \"$(escape_basic "$name")\""
    echo "description = \"$(escape_basic "$description")\""
    if [ -n "$codex_model" ]; then
      echo "model = \"$codex_model\""
      echo "model_reasoning_effort = \"$effort\""
    fi
    echo "sandbox_mode = \"$sandbox\""
    echo "developer_instructions = '''"
    printf '%s\n' "$bd"
    echo "'''"
  } > "$OUT_DIR/$name.toml"
  count=$((count + 1))
done

echo "Transpiled $count agents into $OUT_DIR"
